language: c
sudo: false

env:
  global:
  # GH_BOT_TOKEN (facebook-github-bot-0)
  - secure: I1W8xlf8Ojxkc92n8Rb9AGX7kdCk0DeWEPd6PKRrGQO0FtyCkcvxNo+wp6ApQI7+NqkuFRVngHVOQOd3AqR57IFiSjZ+Cj/BJyg6WOo92olkAAP0OWihmCj53d2xDpp7LaM99srPbZXYE5vSTTKBX/5Soz9UghzsI5Q1ECmV5fU=
  # S3_ID
  - secure: 0EVq9e+b8n1tyMJtWNRMbZvrF7Rp72Zi07HU4bsPgL3eM6nTXa0i2KotgI9P3h4TOUhcDrQXT4oJemchjLsH5yMIbaDycfoou2q0ePit03YDLj/iAIkuf8s+coZWgUTGoMp8TtmDsgrhoLOb5DBVL3PpLQ6jSuoppzysl4iOQ50=
  # S3_SECRET
  - secure: W59c7k40PEKcCqXjbMHVJcIdKgyHkyyTlprU1zTxNneANXxtPu54Gaz84BfHVgq3SK0G+Eqyr19eZTQ4yhfnZzt0TXgfiyYTmPN5ifLJd1x4C56ndXQmSdhR05To9/k9gLlFXoNxDh6rrP+zq2Zp5KbxHTWrm91a21BUGLqnANY=
  # CLOUDFRONT_ID
  - secure: Jr+6c6pF5H0lP4Kt6evlf/xYD/Qjoms3HK7lw1kg8lzwoEXPD3MezgkpOktU8ZBllGolc+ou23h+3hgJwvqi7ANmjzfxyVDdpB7Kiw4y2pEm6tAXYzmatSDb401u7+2sb2H/aSe8yikNrVrizvqaJrDOGeptCBjXQF+a2lNeMC0=

# NOTE: We set the compiler to a bogus "no-op" bash command (":") to work around
# a Travis caching limitation: the cache slug only depends on the compiler name,
# not any other environment vars, so we fake the compiler name to change the
# cache slug.
#
# Alternatively, if Travis had ocaml support, it would presumably include the
# ocaml version in the slug like it does for other languages.
#
# See https://github.com/travis-ci/travis-ci/issues/4393
matrix:
  include:
    - compiler: ": Linux, ocaml 4.02.1, opam 1.2.0"
      os: linux
      env: OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0

    - compiler: ": Linux, ocaml 4.01.0, opam 1.2.0"
      os: linux
      env: OCAML_VERSION=4.01.0 OPAM_VERSION=1.2.0

    - compiler: ": Linux, ocaml 4.02.1, opam 1.1.1"
      os: linux
      env: OCAML_VERSION=4.02.1 OPAM_VERSION=1.1.1

    - compiler: ": Linux, ocaml 4.01.0, opam 1.1.1"
      os: linux
      env: OCAML_VERSION=4.01.0 OPAM_VERSION=1.1.1

    - compiler: ": Mac, ocaml 4.02.1, opam 1.2.0"
      os: osx
      env: OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0

addons:
  apt:
    packages:
    - libelf-dev
    - aspcud

install: bash -e resources/travis/install_deps.sh

script: bash -e resources/travis/build.sh

before_deploy: bash -e resources/travis/before_deploy.sh

cache:
  directories:
  - $HOME/.flow_cache

before_cache:
  - rm -rf $HOME/.flow_cache/ocaml-*/.opam/log

deploy:
# upload releases to github, from both Mac and Linux
- provider: releases
  api_key:
    # facebook-github-bot-0
    secure: I1W8xlf8Ojxkc92n8Rb9AGX7kdCk0DeWEPd6PKRrGQO0FtyCkcvxNo+wp6ApQI7+NqkuFRVngHVOQOd3AqR57IFiSjZ+Cj/BJyg6WOo92olkAAP0OWihmCj53d2xDpp7LaM99srPbZXYE5vSTTKBX/5Soz9UghzsI5Q1ECmV5fU=
  repo: facebook/flow
  skip_cleanup: true
  file_glob: true
  file: flow-*.zip
  on:
    tags: true
    condition:
    - $OCAML_VERSION = 4.02.1
    - $OPAM_VERSION = 1.2.0

# Deploy the website
- provider: script
  repo: facebook/flow
  script: bash -e resources/travis/deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition:
    - $TRAVIS_TAG != "" || $TRAVIS_BRANCH = "master"
    - $TRAVIS_OS_NAME = linux
    - $OCAML_VERSION = 4.02.1
    - $OPAM_VERSION = 1.2.0

notifications:
  email:
    recipients:
      - flowtype@fb.com
  irc:
    channels:
      - "chat.freenode.net#flowtype"
    on_success: change
