language: c
sudo: false

os:
- linux
- osx

env:
  matrix:
  - OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0
  - OCAML_VERSION=4.02.1 OPAM_VERSION=1.1.1
  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.2.0
  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.1.1
  global:
    # GH_BOT_TOKEN
    secure: I1W8xlf8Ojxkc92n8Rb9AGX7kdCk0DeWEPd6PKRrGQO0FtyCkcvxNo+wp6ApQI7+NqkuFRVngHVOQOd3AqR57IFiSjZ+Cj/BJyg6WOo92olkAAP0OWihmCj53d2xDpp7LaM99srPbZXYE5vSTTKBX/5Soz9UghzsI5Q1ECmV5fU=

matrix:
  exclude:
    - os: osx
      env: OCAML_VERSION=4.02.1 OPAM_VERSION=1.1.1
    - os: osx
      env: OCAML_VERSION=4.01.0 OPAM_VERSION=1.1.1

addons:
  apt:
    packages:
    - libelf-dev

script: bash -ex .travis-ci.sh

before_deploy:
- rvm use 2.2 --install --binary # for Jekyll
- gem install --no-rdoc --no-ri github-pages

deploy:
  provider: script
  repo: facebook/flow
  script: resources/travis/deploy.sh
  skip_cleanup: true
  condition: "$OCAML_VERSION = 4.02.1 && $OPAM_VERSION = 1.2.0"

notifications:
  email:
    recipients:
      - flowtype@fb.com
  irc:
    channels:
      - "chat.freenode.net#flowtype"
    on_success: change
