version: '{build}'
clone_folder: C:\projects\flow
os: Visual Studio 2015
platform: x64
environment:
  matrix:
    - ocaml_version: 4.02.1
      ocpwin_version: 4.02.1+ocp1-full-mingw64-20160113
      ocpwin_zip: C:\ocpwin64-20160113-4.02.1+ocp1-full-mingw64.zip
      ocpwin_uri: http://www.ocamlpro.com/pub/ocpwin/ocpwin-builds/ocpwin64/20160113/ocpwin64-20160113-4.02.1+ocp1-full-mingw64.zip
      ocpwin_cache:
        secure: nAAkq86Atkhs9oJsldlsU2ASc6mx7e+3B/YxNJQlKgKFHN0aBJO7iy1Em/3hrhx1fJbotmmy7AbceuLZmgPIUnCUATEx+cYYl9FpGsvo2qQELZixyR/KtUqqJdFPJ+WWpj69FgEKZMaUC4BrFm5/X4KDhr+eGjumXbvtdeFgZaOt07CIaWSgcN2nCroK41Cq/LAkTRz3fm5Wsi8TXuofTCjzaDaEF4i3ZyUgb8+MuJQT7JD7iU8bTLaBAFQmcCEtVIHnRepjLledmUATDg6vzQ==
#    - ocaml_version: 4.01.0
#      ocpwin_version: 4.01.0+ocp1-full-mingw64-20160113
#      ocpwin_zip: C:\ocpwin64-20160113-4.01.0+ocp1-full-mingw64.zip
#      ocpwin_uri: http://www.ocamlpro.com/pub/ocpwin/ocpwin-builds/ocpwin64/20160113/ocpwin64-20160113-4.01.0+ocp1-full-mingw64.zip

install:
- ps: C:\projects\flow\resources\appveyor\install.ps1

build_script:
- ps: C:\projects\flow\resources\appveyor\build.ps1

test_script:
- ps: C:\projects\flow\resources\appveyor\test.ps1
